name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Got an idea? Let us know! Fill in as much detail as you can.
  - type: input
    id: software
    attributes:
      label: Software / Project
      placeholder: "example-app"
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: "I often find myself..."
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "It would be great if..."
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "I also thought about..."
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: "Screenshots, references, etc."
